name: 'Run Test'

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn
      - name: Run Test
        run: yarn test
